AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'log/**/*'
    - 'tmp/**/*'
    - '**/Gemfile'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/ModuleFunction:
  EnforcedStyle: extend_self

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 13

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'app/models/concerns/*'
    - 'app/controllers/concerns/*'

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'

Rails/HttpPositionalArguments:
  Enabled: false
