AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'log/**/*'
    - 'tmp/**/*'
    - '**/Gemfile'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/ModuleFunction:
  EnforcedStyle: extend_self

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'

Rails/HttpPositionalArguments:
  Enabled: false
