linters:
  UnnecessaryMantissa:
    enabled: false

  LeadingZero:
    style: include_zero

  ColorVariable:
    enabled: false
    #exclude:
    #  - '_colors.scss'
    #  - 'user_colors.scss'

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false
