language: ruby
cache: bundler
rvm: 2.3.3
bundler_args: "--without production development"
services: postgresql

env: # workaround
  - "TEST_SUITE=units"
matrix:
  include:
    - env: "TEST_SUITE=functionals"
      addons:
        apt:
          packages: texlive-latex-base
    - env: "TEST_SUITE=integration"
      before_install: scripts/integration.sh

before_script:
- psql -c 'create database kontes_terbuka_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- cp .env.default .env
script: "bundle exec rake test:$TEST_SUITE"
after_script:
- rubocop -D -f simple --except AbcSize,MethodLength
- haml-lint --exclude-linter LineLength app/views
- scss-lint app/assets/stylesheets
- eslint app/assets/javascripts
