language: ruby
rvm:
  - 2.3.1
bundler_args: --without production development
services:
  - postgresql

notifications:
  webhooks:
    urls:
      - https://ktom.tomi.or.id/travis
    on_success: always
    on_failure: always
    on_start: always

before_script:
  - psql -c 'create database kontes_terbuka_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/initializers/line_targets.rb.default config/initializers/line_targets.rb
script:
  - bundle exec rake
after_script:
  - rubocop -D -f simple --except AbcSize,MethodLength
  - haml-lint --exclude-linter LineLength app/views
  - scss-lint app/assets/stylesheets
  - eslint app/assets/javascripts
