linters:
  UnnecessaryMantissa:
    enabled: false

  LeadingZero:
    style: include_zero

  ColorVariable:
    exclude:
      - '_colors.scss'
      - 'user_colors.scss'

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false
